[package]
name = "play_sound"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Awarty/play_sound"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17.1"

